# Generated by Django 2.2.4 on 2019-08-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20190808_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='todoapp.Hashtag'),
        ),
    ]
