# Generated by Django 2.2.4 on 2019-08-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20190811_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='invalidity',
        ),
    ]
